### ISSUE TITLE
Dueling Nemeses

### ISSUE THREAD

**Issue by zeriley** [ToroCraft/NemesisSystem#10]
We may want to rethink the dueling nemeses, because this will often result in very few nemeses existing.  Once players establish a base, most of their deaths will be in the same few chunks, probably, so the nemeses will just keep dueling and killing each other, leaving just a few nemeses.  Perhaps they should queue up, so that after you kill one nemesis and re-enter the chunk, the next nemesis would be present.  

Alternatively, there could be a hierarchy and nemeses could co-exist only if they were different levels.  Like one reported to the other.  But if they are the same level, then they'd duel.

**Comment by frodare** [comment]
This currently only happens when a new Nemesis is forced in by a player death and the Nemesis limit was exceeded.

https://github.com/ToroCraft/NemesisSystem/blob/51c0b8459d232736c9e7e5cb76c812e717059d52/java/net/torocraft/nemesissystem/handlers/DeathHandler.java#L95-L95

**Comment by zeriley** [comment]
Ok, looked like it was happening every time based on the logs.
