### ISSUE TITLE
Nemesis Relationships

### ISSUE THREAD

**Issue by frodare** [ToroCraft/NemesisSystem#11]
From: http://shadowofmordor.wikia.com/wiki/Nemesis
Relationships - Some of the Nemeses may have some kind of relation to other Nemeses. This usually involves a rivalry between two Nemeses, and Talion will constantly find these two doing missions against each other until one of them dies. Several Captain Nemeses can serve as bodyguards to the Warchiefs of the region. When the Warchief appears to face Talion, all his bodyguards will always be present, although the inverse is not always the case; the bodyguards can be found alone.

**Comment by zeriley** [comment]
So how do we want to adapt this to our mod?

- Lower-level nemeses in the same or neighboring chunks can spawn as bodyguards for a higher-level nemesis
- Some nemeses may be rivals, so therefore more likely to duel?  In Mordor, you can cooperate or assist in other ways one nemesis over his rival.  To a point, I believe, where they will fight for you.  Maybe a nemesis can become your companion?  Would have to override a lot of AI that way, though...
- A level 10 nemesis will have all nemeses as bodyguards?

**Comment by frodare** [comment]
I would really love to see the middle point added, where players can affect the nemeses somehow.

**Comment by zeriley** [comment]
Hah, we could make it like with animals where you can feed a nemesis an appropriate item and it would change his hostility towards you.  Feed a zombo some raw animal meat and the hearts would pop up.  If you do that enough, he becomes a companion.

**Comment by pandapaul** [comment]
Hostile mob -> companions could be its own feature mod.  That would be pretty neat.

**Comment by werff** [comment]
I would love that!
The nemesis internal relationship and the option, for the player, as separate but compatible mod, to "tame/ally" hostile mobs and the nemesis.
