### ISSUE TITLE
Logging System

### ISSUE THREAD

**Issue by frodare** [ToroCraft/NemesisSystem#13]
Record key events for nemesis in their Nemesis NBT.  The GUI will provide a way for players to use it to view their history.

**Comment by zeriley** [comment]
We can use the events system created to handle notifications. Let's discuss what key events should be logged and what the log would look like, as a java class.

Key events:
- kill player/killed by player
- win duels/lose duels
- promotions
- creation of nemesis
- fled successfully

Java fields:
```
EventType (enum) type; = correlates to key events above
Map<String, String> eventDetails; 
// would be different values based on type; i.e. duels would contain the 
// name of the nemesis killed, promotion would contain achieved level, etc.
```
Gives us the most flexibility, but is also not self-documenting.

**Comment by zeriley** [comment]
I didn't actually get this to work, and I'm having issues which I will come back to.
