### ISSUE TITLE
Nemeses flee

### ISSUE THREAD

**Issue by zeriley** [ToroCraft/NemesisSystem#14]
At low health, maybe the nemesis should flee (or only nemeses with certain traits would flee) to live to fight another day.  On successful fleeing, they could receive more bodyguards on next spawn, but only be at 80% health or something and maybe lost a piece of armor.

**Comment by bdevo1896** [comment]
More on this suggestion, I think the nemesis should disappear after they get a certain block distance away from the nearest player.
