### ISSUE TITLE
Drop nemesis armor on death

### ISSUE THREAD

**Issue by zeriley** [ToroCraft/NemesisSystem#16]
https://github.com/ToroCraft/NemesisSystem/blob/master/java/net/torocraft/nemesissystem/handlers/DeathHandler.java#L118

TODO says to drop all nemesis items, but I think we should just drop a random piece of armor.

**Comment by frodare** [comment]
I really think we should drop all items.  We should damage them though.  I would also like to show the items in the gui so player could be encouraged to attack them.

**Comment by zeriley** [comment]
Do they gain all new armor after you kill them, then?  As long as they are heavily damaged, I'm fine with dropping all.

**Comment by frodare** [comment]
yeah, this made more sense in the sudden death model. But yeah, a new set of armor that is run through the enchantment function one per each level

**Comment by zeriley** [comment]
Maybe learn from Diablo and give a random chance at dropping a fully-intact "legendary" piece of equipment.  Might get @pandapaul to play with us...

**Comment by frodare** [comment]
#torofishing
