### ISSUE TITLE
Add support for secondary traits

### ISSUE THREAD

**Issue by zeriley** [ToroCraft/NemesisSystem#26]
https://github.com/ToroCraft/NemesisSystem/blob/master/java/net/torocraft/nemesissystem/util/HandleNemesisTraits.java#L38

At level 5, nemeses will earn a second trait.

**Comment by frodare** [comment]
My vote is to mix it up a bit by a random function like:
```
chance_for_additional_trait = 1 / (10 * num_of_current_traits)
```

**Comment by frodare** [comment]
Also, secondary traits should be used less often, maybe half the time of primary ones or less

**Comment by zeriley** [comment]
Some traits will counter each other, though.  Like Double_melee and arrow.  I guess their appearance is based on their primary trait, but they get the abilities of other traits

**Comment by frodare** [comment]
Yes, primary affects there visual weapon.
