### ISSUE TITLE
Nemesis Weaknesses

### ISSUE THREAD

**Issue by frodare** [ToroCraft/NemesisSystem#43]
When a weakness is activated, red down arrow particles would appear around the nemesis.

Weakness can be assigned to nemeses similarly to traits.
Starting weakness: Hydrophobe (entity takes damage when in water and will flee from it)

**Comment by zeriley** [comment]
- Pyrophobia: Fire will cause nemesis to stop attacking and run around like the Village Lord instead, ideally with his arms up
- Disco Fever: Rhythmic crouching or playing a note block or jukebox causes nemesis to dance to the beat, leaving him open for attack
- Greedy: Throwing a gold ingot on the ground will cause the nemesis to stop attacking and go retrieve the gold; placing a gold block will make him stand in worship of the gold block, not attacking for 10 seconds or so
- Gluttony: Same effect as greedy with gold ingots, but with food; satiation affects how long the nemesis stands idle
- Amorous: Players of the opposite gender (Steve model for male; Alex model for female) cause nemesis to stand idle until first hit

**Comment by frodare** [comment]
Wood Allergy (double damage when using wood weapons)
same with gold and stone

**Comment by frodare** [comment]
Add a weakness for each potion and each type of tipped arrow

**Comment by frodare** [comment]
Phasmophobia: fear of ghosts, nemesis will have trouble attacking a player when wearing a pumpkin on their head, maybe they would need to wear white armor too?

**Comment by zeriley** [comment]
Could do some kind of snowman thing, too.  Or just snowballs in general, would immobilize the nemesis.  Or change all his attacks to snowballs for a few seconds.

Similar thing with eggs.

**Comment by frodare** [comment]
ichthyophobia: Nemesis will run and stop attacking for a moment when fish is thrown at him

**Comment by zeriley** [comment]
Animal lover: Killing an animal (maybe specific animals depending on the nemesis) in front of the nemesis causes it to stop and cry  (if we wire in @mrprim 's suggestion to chat taunts, he could yell, "You MONSTER!  Now you must die!" or "That was my favorite sheep!" or some such)

**Comment by frodare** [comment]
Chicken: afraid of chickens

**Comment by zeriley** [comment]
Gluttony and Greed have been implemented.  Spiders have a hard time picking up items.  Something we need to look into at some point.

**Comment by zeriley** [comment]
The following weaknesses have been implemented:
HYDROPHOBIA, PYROPHOBIA, WOOD_ALLERGY, GOLD_ALLERGY, STONE_ALLERGY, GREEDY, GLUTTONY, CHICKEN

We may change the behavior of some of these, but for now, closing this issue.
