### ISSUE TITLE
Body Guards can spawn inside blocks

### ISSUE THREAD

**Issue by frodare** [ToroCraft/NemesisSystem#47]

**Comment by zeriley** [comment]
Bodyguards OP, pl0x nerf bung0.

**Comment by zeriley** [comment]
This actually gives me an idea for a new mob.  It'd be similar to the Pile Driver Mini Goomba (https://strategywiki.org/wiki/Super_Mario_Bros._3/Enemies) from SMB3.  The mob just looks like a block of dirt or whatever is appropriate for the biome, but when you get close, it gets arms and legs and attacks you.

Edit: I guess the shulkers are kind of already like that.

**Comment by pandapaul** [comment]
BUNGO PLZzzZZzzZ

**Comment by frodare** [comment]
@mrprim (the Nerd Whisperer) please translate
