### ISSUE TITLE
Increased and more difficult mob spawns around nemeses

### ISSUE THREAD

**Issue by frodare** [ToroCraft/NemesisSystem#48]
This effect should be based off level

**Comment by zeriley** [comment]
What do you have in mind for this?  It already scales to spawn more mobs based on nemesis level.  After level 6, do you want to add in like 3-8 (3 at level 6, 8 by level 10) skeletons?  Maybe random chance for a wither skeleton or two, also?

**Comment by frodare** [comment]
The idea was to have the Nemeses affect their surrounds even when not spawned.  So, for example, a level 10 nemesis might cause 3 zombies to spawn where only one would normally spawn for a 1k block radius.  Also they spawns would be stronger, similar to how mobs spawns are affected by the moon cycle.

**Comment by zeriley** [comment]
Ah, that's a cool idea.  Maybe in figuring this out, we could find a better way to spawn toros, also.

**Comment by frodare** [comment]
Ideas from xwerffx (https://minecraft.curseforge.com/projects/nemesis-system?comment=18)

![nemesis-ideas](https://user-images.githubusercontent.com/795621/30294290-96e6094e-970a-11e7-96cb-f20df0c16222.png)

**Comment by zeriley** [comment]
Will look at this more when I get home (if I can pull myself away from Destiny long enough), but I really like the idea of having to kill half the bodyguards to summon the nemesis.
