### ISSUE TITLE
Nemesis Strengths

### ISSUE THREAD

**Issue by zeriley** [ToroCraft/NemesisSystem#49]
When a strength is activated, green up arrow particles should appear around the nemesis.

- Precision: attacks have a chance to ignore armor
- Yolk's on You: hitting nemesis with an egg will infuriate him and increase his attack power for 5 seconds
- Inflamed Passion: setting nemesis on fire causes his defense to sharply rise for 5 seconds
- [Material] Immunity: weapons made of [material] do far less damage
- Burning Shame: nemesis's defense increases the more times he has been killed
- Bloodlust: after killing a player, a nemesis's strength is increased until he is killed
- Not Chicken: chickens enrage the nemesis, increasing strength

**Comment by frodare** [comment]
moved to ToroTraits
