### ISSUE TITLE
Nemesis information discovery

### ISSUE THREAD

**Issue by zeriley** [ToroCraft/NemesisSystem#50]
Certain events/items/etc. would reveal information about a nemesis.  A random piece of information would be revealed:
- Location
- Name and appearance
- Equipment details
- Strength(s)
- Weakness(es)

Information procurement methods:
- low chance of information gained from killing random mobs
- books found in chests throughout the world would contain nemesis information
- converting a zombie villager back to a villager is guaranteed to provide info
- one nemesis's bodyguard would be flagged as an information source (called a "worm" in Shadows of Mordor) and killing him would provide information

**Comment by pandapaul** [comment]
In each of the information procurement methods, would it be true to the spirit and viable for a [Written Book](http://minecraft.gamepedia.com/Written_Book) to be the information source?

OR should it be an entirely new item?

**Comment by zeriley** [comment]
Yes, I'm glad you brought this up, because I was thinking about it in bed last night and would have forgotten to put my thoughts here.

I was thinking about how this would work and for what players the information would be unlocked.  My first thought was just the person who did the action, but that would be frustrating for people playing as a group.  Unlocking for all players would be frustrating for people who play against each other.  So I think every procurement method should drop a written book (if we can make that work) and whoever uses the book gets the information, so that you can share the book with your teammates but not your enemies.

@frodare can we persist the unlocked info on each player and will your GUI be able to read from the player's NBT (I assume)?

**Comment by frodare** [comment]
Yes, we can persist that info on players.  We will probably need to make a new book like item.  When it is read it can unlock some information about a nemesis for that player.

**Comment by zeriley** [comment]
Yeah, I agree.  I doubt Forge has a PlayerReadBook event...
