### ISSUE TITLE
Combo with Everlasting Abilities

### ISSUE THREAD

**Issue by Darkmega18** [ToroCraft/NemesisSystem#78]
https://minecraft.curseforge.com/projects/everlastingabilities

Everlasting abilities has the power to give mobs abilities and have them radiate or cause effects around the target and give them sparkly particle effects. Perhaps you could find away to borrow similar buffs or hook into this so that it adds some everlasting abilities to the nemesis' when they're spawned. Even more bad times.

**Comment by frodare** [comment]
That looks like it adds a way for players to have permanent potion effects.  I was thinking of adding area based potion effects to the nemeses, and your idea helps support that idea.  Currently there is a Brew Master trait that gives the nemeses the ability to throw potions, but that is limited to the standard potions a witch would use.

I created a new issue to add this feature:
Area Potion Effects Trait #12
If that doesn't fully cover what you were thinking please let me know,
Thanks!

**Comment by Darkmega18** [comment]
I might be confusing the way it's worded in the config with it spawns them with a possible drop of the ability rather than the ability actually working from the mob in question as well as having them drop it for the player to apply.

**Comment by frodare** [comment]
I will download that mod and try it out, it looks pretty cool. I think it will make more sense after using it.

**Comment by frodare** [comment]
I played around with Everlasting Abilities a little, were you thinking of the Nemeses have abilities like the ones in that mod, or dropping ability bottles?  For the first one, that would be mostly accomplished from the issue I created earlier.

**Comment by Darkmega18** [comment]
yeah, it was them having abilities like them. Basically traits that buff them or in some cases provide buffs to their allies nearby or debuffs to the player. But nothing cheesy like "spontaneously catching fire when near" or instant wither any time they're close. But if you had to do those kinds of things they could have a timer on them based on the severity and so they pulse in a short distance then turn off for 10 seconds, or they could require the nemesis to be a certain distance to you for a set time before their effect takes hold of you. Then meanwhile when they have traits that can have particle effects coming off them for some of the less obvious effects.
