### ISSUE TITLE
BUG: Crap ton of health and Nemesis Fall

### ISSUE THREAD

**Issue by werff** [ToroCraft/NemesisSystem#80]
The Nemesis (guards, in nearly all cases) have like 400 hearths of health (so 800 health), some times it happens.
When a guard kills the player (well, me) it's health gets to that high amount, some times it happens with the Nemesis too.

Also, when a Nemesis dies from fall damage doesn't count as killed and it doesn't lost a level (or permanently die).
This last one happened to my 4 times in a row XD, it could be bad luck... But better to be sure.

Thanks for reading

**Comment by frodare** [comment]
I bet this is related to the buffed mob spawns. Maybe I forgot to exclude guards.  If so I will try to get that fixed tonight.

**Comment by werff** [comment]
Also.... a ton of damage.
One zombie one shot me while I was in full diamond XD

**Comment by frodare** [comment]
So I actually did exclude guards from being buffed.  Can you post a screen shot here using [ToroHealth](https://minecraft.curseforge.com/projects/torohealth-damage-indicators) or similar tool showing their health.  That might help me figure out what is going on quicker.

**Comment by werff** [comment]
The health bug (I don't know why, disapeared XD) but the guards do 12 dmg (6 hearts) with their stone swords XD Is that intended?
Also 60hp zombies XD

**Comment by frodare** [comment]
That is the buffed spawns which is proportional to the distance from the nemesis's domain and his level.  I think I will add config so that can be adjusted.

**Comment by werff** [comment]
![2017-09-25_20 59 19](https://user-images.githubusercontent.com/4353439/30825775-8446ce38-a234-11e7-801a-06a99cbb6614.png)
My bad, it still happens...
I found this guys outside my mine XD

**Comment by frodare** [comment]
Is it rare, like only on out of 20 or 30 zombies?  If so I have an idea of what it might be.

**Comment by werff** [comment]
And he oneshoted me when I was leaving it XD
While wearing a full iron armor... Scary man


Still, for the difficulty thing, I would make more mob spawning and better equipped mobs, over more health and dmg...

**Comment by werff** [comment]
I mean, I would be more "fun" trying to survive 12 iron equiped zombies and 3 zombies of 12 dmg por hit (unarmored) and 50hp

**Comment by frodare** [comment]
In all my testing, I have only been able to get zombies up to a health of 45.  Do you have another mod that could be increasing health too?

**Comment by werff** [comment]
I don't have any mod that modifies the health of the mobs
