### ISSUE TITLE
Improve non-player death of Nemesis 

### ISSUE THREAD

**Issue by frodare** [ToroCraft/NemesisSystem#81]
from #80:
Also, when a Nemesis dies from fall damage doesn't count as killed and it doesn't lost a level (or permanently die).
This last one happened to my 4 times in a row XD, it could be bad luck... But better to be sure.
~werff

**Comment by frodare** [comment]
Maybe we could fix this by checking if the nemesis had taken damage from a player within the last 15 or so seconds, and if they had, contribute the death of the nemesis to that player.

**Comment by werff** [comment]
It the Némesis get's killed by an NPC or other mob it Works too, but not fall dmg

**Comment by frodare** [comment]
I assume fire, out-of-world and explosion deaths would have this problem too.

**Comment by werff** [comment]
![2017-09-25_21 06 44](https://user-images.githubusercontent.com/4353439/30826219-0c055654-a236-11e7-9e8c-5af0d0ebaa88.png)
Your guards and sentries can do the job!
And it counts as a defeat for the nemesis

**Comment by frodare** [comment]
LOL "Oclwell the Giggles has been demoted after losing a fight with a Sentry" ... that cracks me up for some reason.  Well he should know better than to settle in a province ;)

**Comment by werff** [comment]
Also, on a side note, when the nemesis reach level 6-7 and onwards, their reach is very high, could you lower it a bit? Just that XD

**Comment by frodare** [comment]
File a new issue for that, it sounds like a bug to me which really needs to get fixed.
