### ISSUE TITLE
Quality of Life Suggestion: Intel

### ISSUE THREAD

**Issue by Darkmega18** [ToroCraft/NemesisSystem#82]
A suggestion on how to make intel better, rather than having a bunch of books that clog inventories.

Have intel mobs spawn which have enchanted particles floating around their head. When these mobs die drop an item that represents "intel", probably just the intel symbol from shadow of mordor.

This intel item can then be used to go into the nemesis menu and scroll to any nemesis that is available. By clicking on them you can use one intel item to request a piece of intel about that nemesis to unlock knowledge about their items, their traits or their location which will consume one piece of intel from the stack.

Unlocking any of the 3 pieces of intel on any nemesis reveals their name and looks.

Intel is known per player, and you can share intel to another player by having an unsigned writing book in your hand. Then on the nemesis screen you can hit a button that turns the writing book into a book that transfers all knowledge from the player that created it to the person who reads it and then deletes the book.

this system would then also save you from getting duplicates of intel like I sometimes get after I've gotten a lot (like a whole chest worth of it).

**Comment by frodare** [comment]
Interesting ideas.  As it stands right now, that is a bigger change then I would want to invest into this mod right now.  I totally can see the annoyance of having to keep a bunch of books around though.

Maybe a solution to solve that, without having to rebuild the entire system, would be to allow the discovery books to be crafted together for a given nemesis.  That would mean you would only need to keep on book per nemesis.  That might even be a bigger change than I am thinking, but if not, it would be a decent solution.

**Comment by zeriley** [comment]
Yeah, I like that idea @frodare.  I don't remember what we ended up storing on the books, but it seems like merging the NBT would be very doable.

**Comment by Darkmega18** [comment]
I see. :V yeah, usually once I get a soul gems grinder going cause of absorbing all the spawners in a roguelike dungeon I end up with a rediculous amount of unread nemesis books that I don't really want to look at cause then they expand and a lot of the time I get doubles (although atleast the doubles stack). can you atleast check per player what they have learnt and what they haven't and just give the player reading it intel that isn't double upped? That way in a co-op setting you could have just one intel gathering player who then shares intel with the rest of his group by having the books be accessible afterwards in a chest etc to prevent book overflow. Not that I don't like having a bibliocraft library with some contents.... Brings a new meaning to the term "Read" in fighting games. Go to the library and read about your enemy and what he'll do. xD

**Comment by frodare** [comment]
@Darkmega18 I organized your ideas into three different tasks that I think should be doable.  The first one should be pretty easy, but would make the intel process much easier, so I was thinking about adding third idea too to balance it. Thoughts?

1) when reading an unread book for the first time, only select a discovery the user doesn't have or leave the book unread

2) allow books to be crafted together

3) only drop books when players kill the entity?  Maybe add a config for this.

**Comment by Darkmega18** [comment]
That is entirely fine. most of my grinders are usually manual grinders with wooden spikes or measured pitfalls to bring them to low HP so I can use looting and stuff on them and get rare drops etc. :)

**Comment by Darkmega18** [comment]
Err. RIP nemesis system mod. :V

**Comment by Darkmega18** [comment]
rip nemesis system
