### ISSUE TITLE
Crash after Nemesis marched into battle

### ISSUE THREAD

**Issue by belathus** [ToroCraft/NemesisSystem#86]
https://gist.github.com/belathus/576a51f974e1748d6e400bd589f28b25

One nemesis "marched into battle" then shortly after, we started getting a crash. The crash happens when one particular player joins the server, so I guess that is who is being attacked.

**Comment by frodare** [comment]
I think this is caused by using the 1.12.1 version in minecraft 1.12.2.

**Comment by belathus** [comment]
Any chance this'll get an update to 1.12.2, then?

**Comment by frodare** [comment]
Unfortunately, all of the torocraft developers have moved on to other projects. This is top of the list if development picks back up.
