### ISSUE TITLE
Branding Nemesis/Normal (nemesis allowed) mobs?

### ISSUE THREAD

**Issue by werff** [ToroCraft/NemesisSystem#87]
Just as a suggestion, with this you could march your own "army" against another ones army, making it more like the games, and allowing you to gear and field troops agains other players and the normal nemesis!

And I don't know how to mark things as "suggestion/enchancement" on GitHub XD

**Comment by frodare** [comment]
That would be really cool.  I had a similar idea with ToroQuest, but never got far enough to pull it off.

**Comment by werff** [comment]
Yep, with the #48, and my [idea](https://user-images.githubusercontent.com/795621/30294290-96e6094e-970a-11e7-96cb-f20df0c16222.png ) the mod will get very cool XD
